// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations"
    },
    datasource: {
        // Prisma CLI tools should use a direct database connection when the app
        // itself connects through a pooler like PgBouncer/Supavisor.
        url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"]
    }
});
